FROM --platform=linux/amd64 apache/airflow:2.8.0

RUN pip install airflow-provider-great-expectations==0.2.7 \
                astronomer-cosmos==1.3.2 \
                dbt-core==1.7.9 \
                dbt-postgres==1.7.9